version: "3.8"
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATABASE: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

  app:
    build: .
    command: /usr/src/app/run.sh
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles/
      - ./media:/usr/src/app/media/
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT}:8000
    env_file: .env
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - ALLOWED_HOSTS=localhost,127.0.0.1,tax-calc.simple2b.net
    depends_on:
      - db

volumes:
  db_data:
