version: '3.9'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${LOCAL_DB_PORT}:${DB_PORT}

  app:
    build: .
    command: sh ./run.sh
    volumes:
      - ./:/usr/src/app/
      - templates:/usr/src/app/templates/
      - staticfiles:/usr/src/app/staticfiles/
      - media:/usr/src/app/media/
    ports:
      - ${WEB_SERVER}:${LOCAL_WEB_PORT}:${WEB_PORT}
    env_file: .env
    depends_on:
      - db

volumes:
  db_data: null
  templates:
  staticfiles:
  media: