version: "3.8"
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${LOCAL_DB_PORT}:5432

  app:
    build: .
    command: /usr/src/app/run.sh
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles/
      - ./media:/usr/src/app/media/
    ports:
      - ${LOCAL_WEB_PORT}:8000
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:
